root_dir: ''  # /raid/home/minht/projects/prostate_teus/ProstateCancerClassificationV2
exp_dir: /raid/home/minht/workspace/experiments/vicreg_patch/wp_avg_str32_in_core
data_root: /raid/home/minht/workspace/datasets/patches/patch_48x48_str32/*/*_core
log_freq_time: 60
arch: resnet50  # resnet50
mlp: 8192-8192-8192
seed: 6

# Optim
optimizer: lars # adamw lars
epochs: 100
batch_size: 128  # 2048
base_lr: 0.2
#base_lr: 0.00075
weight_decay: 1.0e-6  # 1.0e-6 0.05
end_lr_ratio: 0.001
warmup_epochs: 10
maps_lr_ratio: 0.1

# Loss
sim_coef: 25.0  # Invariance regularization loss coefficient
std_coef: 25.0  # Variance regularization loss coefficient
cov_coef: 1.0   # Covariance regularization loss coefficient

# Running
num_workers: 40
device: cuda

# Distributed (not used currently)
world_size: 1
local_rank: -1
dist_url: 'env://'

# ConvNext args
drop_path_rate: 0.1
layer_scale_init_value: 0.0
in_channels: 20